import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-screen overflow-hidden">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
			>
				{/* <nav className="mb-8">
					<h1 className="font-black">
						<Link href="/">CS 6460: Term Project</Link>
					</h1>
				</nav> */}
				{children}
			</body>
		</html>
	);
}
